### PR TITLE
Add message and cost limits to run methods

### LINKED ISSUE #70: Add `message_limit` (number of model messages) and `cost_limit` to `run()` methods
To mitigate the risk that an agent gets into an infinite loop.

### PR DESCRIPTION
**Pull request by The-CodeINN**
Fixes #70

Add `message_limit` and `cost_limit` parameters to `run()`, `run_sync()`, and `run_stream()` methods in `pydantic_ai_slim/pydantic_ai/agent.py`.

* **pydantic_ai_slim/pydantic_ai/agent.py**
  - Add `message_limit` and `cost_limit` parameters to `run` method signature.
  - Add `message_limit` and `cost_limit` parameters to `run_sync` method signature.
  - Add `message_limit` and `cost_limit` parameters to `run_stream` method signature.
  - Implement logic to check `message_limit` and `cost_limit` in `run` method.
  - Implement logic to check `message_limit` and `cost_limit` in `run_stream` method.

* **tests/test_agent.py**
  - Add unit tests for `message_limit` and `cost_limit` parameters in `run` method.
  - Add unit tests for `message_limit` and `cost_limit` parameters in `run_sync` method.
  - Add unit tests for `message_limit` and `cost_limit` parameters in `run_stream` method.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pydantic/pydantic-ai/pull/188?shareId=bbbfa349-c159-468c-a557-05f55fb551af).

### CODE REVIEW

**Comment by samuelcolvin** [comment]
@The-CodeINN did you close this intentionally? We'd love to get this supported?

**Comment by The-CodeINN** [comment]
Not intentional. I'd reopen this.

**Comment by sydney-runkle** [comment]
I think https://github.com/pydantic/pydantic-ai/pull/227 might address the cost limit here...

**Comment by sydney-runkle** [comment]
I think we should probably refactor this now to add things to the `ModelSettings` structure.

**Comment by richy-a11y** [comment]
> I think #227 might address the cost limit here...

I can close this then

**Comment by sydney-runkle** [comment]
Closing for now, we're going to take a slightly different approach.

**Pull request closed without merging**
