### PR TITLE
Add support for new Gemini model 'gemini-2.0-flash-exp'

### PR DESCRIPTION
**Pull request by Etelis**
Introduce the new Gemini model to the existing model list.
address issue #216

An easy fix.

### CODE REVIEW

**Comment by janas-adam** [comment]
checked, works well

**Comment by Etelis** [comment]
> checked, works well

Thanks!
Just saw your message on the issue itself. 
maybe we could jointly work on this. 
you could add tests related to it for instance (if you feel like doing so)

**Comment by sydney-runkle** [comment]
@Etelis,

Could you please add this to `pydantic_ai.models.__init__.py` as well? Should just be a one line addition. LGTM otherwise, thanks!

**Comment by Etelis** [comment]
> @Etelis,
> 
> Could you please add this to `pydantic_ai.models.__init__.py` as well? Should just be a one line addition. LGTM otherwise, thanks!

Yeah sure, added.
must have missed that.

**Review by sydney-runkle — APPROVED** [review]
Great, thanks!

**Pull request merged**
