### PR TITLE
Uv workspaces and `pydantic-ai-slim`

### PR DESCRIPTION
**Pull request by samuelcolvin**
Idea is to have:
* `pydantica-ai-slim` with all the logic and optional dependency groups for everything you might want to add
* then `pydantic-ai` becomes a sub package that just has `pydantica-ai-slim[openai,groq,vertexai]` and more as they're added as a dependency
* examples becomes a package too

Trying to use `uv` workspaces to manage that, see https://github.com/astral-sh/uv/issues/9415

### CODE REVIEW

**Comment by johnslavik** [comment]
@samuelcolvin Was it intended for pydantic-ai to put a bare `README.md` in `site-packages/` when installed?
That's what I'm observing, caused by lines:

https://github.com/pydantic/pydantic-ai/blob/556ee0957b729122eadb186c18b3c619d6c98372/pyproject.toml#L128-L129

Short repr:
```bash
uv venv &>/dev/null && \
    uv pip install pydantic-ai &>/dev/null && \
    tree -L1 --filesfirst .venv/lib/*/site-packages/ | \
    grep -E '(.venv/|README.md)' && \
    echo && head .venv/lib/*/site-packages/README.md
```

**Comment by johnslavik** [comment]
It seems that it serves just as a shim artifact that is needed for the wheel to exist.

**Comment by johnslavik** [comment]
Maybe `bypass-selection` could be used. https://github.com/pypa/hatch/discussions/1128
Then we'd have a metadata-only wheel for `pydantic-ai` as a manifest of dependencies.

**Comment by DouweM** [comment]
@johnslavik Feel free to file a PR if you have a better solution!

**Comment by johnslavik** [comment]
> @johnslavik Feel free to file a PR if you have a better solution!

Thanks, sure! Will file an issue and PR to track.

**Pull request merged**
