### PR TITLE
[Feature] General Model

### PR DESCRIPTION
**Pull request by kenjihikmatullah**
Hi @samuelcolvin , hereby I'd like to contribute adding General Model. Hopefully it can be helpful

**Problems**
1. There are lots of LLM service providers, both local and cloud
2. Existing `OpenAIModel` can easily handles them, but the name does not imply that

**Ideas**
Add new `GeneralModel` in which:
1. Can flexibly handle many LLM service providers in general, both local and cloud.
2. The name (GeneralModel) implies that (1)
3. It purely uses REST API, therefore it does not depend on SDK/library of any particular LLM service provider (provider-agnostic). Moreover, people who use `pydantic-ai-slim` does not have to install additional `pydantic-ai-slim[openai]`

This solution is already tested agains [Jan](https://jan.ai/) and [Ollama](https://ollama.com/) on local.

**Rooms for Improvement**
If this is acceptable idea, there are some rooms for improvement
1. Complete unit tests
2. Add docs
3. Tests on more LLMs such as llama.cpp, LocalAI, LM Studio, and Msty
4. Internally improve type safety inside GeneralModel
5. Handle mixed-up json object on a single chunk when do streaming

---

Feedback and suggestions are highly appreciated. Thank you!

### CODE REVIEW

**Comment by Etelis** [comment]
Hey, 
Thanks for that I have been looking for something similar.
IMO, it should be an interface rather then a full implementation, as not all REST APIs are the same regarding the endpoints.
In some sense you have assumes they all use the OpenAPI interface, rather then allowing users to implement an interface.

**Comment by kenjihikmatullah** [comment]
> Hey, Thanks! I’ve been looking for something like this.
> 
> IMO, it would be better to use an interface rather than a full implementation, as not all REST APIs follow the same structure for endpoints.
> 
> It seems like the current approach assumes that all APIs use the OpenAPI standard, rather than giving users the flexibility to implement a custom interface.

Hi @Etelis , thanks for the feedback! I think that's good point to promote Open-Closed Principle. I will try to figure it out to make some abstraction on that so that it is extensible for any other LLMs having different endpoint, payload structure, etc.

**Comment by samuelcolvin** [comment]
I don't see any advantages of this over the current OpenAI model, and many disadvantages in terms of type-safety.

I also think then name is less easy to understand than `OpenAIModel`.

So on balance, I don't think this is a good idea.

**Comment by kenjihikmatullah** [comment]
@samuelcolvin thanks for the feedback!

**Pull request closed without merging**
